### ISSUE TITLE
Does this integration work with SSR? 

### ISSUE THREAD

**Issue by DanielRSnell** [littlesticks/astro-sanity#11]
I was testing out this integration and realized that when I move it over to output: server on netlify, the pages using the client do not function.

**Comment by jaydanurwin** [comment]
Yup it supports SSR! I've tested a live site running on Astro 2.0 through SSR on Vercel. 

You'll want to be sure you're using the latest version of the package (1.1.2) though.

**Comment by aaronm-git** [comment]
doesnt work with astro 4
