### ISSUE TITLE
Missing Type Definitions

### ISSUE THREAD

**Issue by TaraBryn** [littlesticks/astro-sanity#13]
### Code: 
`import { useSanityClient } from "astro-sanity";`

### Error: 
"Cannot find module 'astro-sanity' or its corresponding type declarations.ts(2307)"

### Versions
Astro Version: 1.9.0
astro-sanity version: 1.1.2

### Minimum reproducible example: 
https://codesandbox.io/p/sandbox/interesting-beaver-49l53r?file=%2Fsrc%2Fpages%2Findex.astro&selection=%5B%7B%22endColumn%22%3A29%2C%22endLineNumber%22%3A14%2C%22startColumn%22%3A4%2C%22startLineNumber%22%3A14%7D%5D

**Comment by cktsun1031** [comment]
![image](https://user-images.githubusercontent.com/65409152/212646270-1712befb-7d2d-41db-b852-a60ff4c1dc25.png)

**Comment by ehowey** [comment]
Also commenting about this one - let us know if we can help at all!

**Comment by jaydanurwin** [comment]
Closing this as it should now resolved in `v1.1.3`. Thanks again @gksander!
